"""game table

Revision ID: 878f3b2e391b
Revises: c3ac59333223
Create Date: 2022-05-22 18:02:51.373403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '878f3b2e391b'
down_revision = 'c3ac59333223'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.create_foreign_key(None, 'game', 'game_user', ['user_id'], ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.create_foreign_key(None, 'game', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
