"""game table

Revision ID: c3ac59333223
Revises: 888999783498
Create Date: 2022-05-22 16:44:18.642476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3ac59333223'
down_revision = '888999783498'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_date'), 'game', ['date'], unique=False)
    op.drop_index('ix_game_user_date', table_name='game_user')
    op.drop_index('ix_game_user_user_IPAddress', table_name='game_user')
    op.drop_column('game_user', 'date')
    op.drop_column('game_user', 'score')
    op.drop_column('game_user', 'user_IPAddress')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_user', sa.Column('user_IPAddress', sa.VARCHAR(length=64), nullable=True))
    op.add_column('game_user', sa.Column('score', sa.INTEGER(), nullable=True))
    op.add_column('game_user', sa.Column('date', sa.DATETIME(), nullable=True))
    op.create_index('ix_game_user_user_IPAddress', 'game_user', ['user_IPAddress'], unique=False)
    op.create_index('ix_game_user_date', 'game_user', ['date'], unique=False)
    op.drop_index(op.f('ix_game_date'), table_name='game')
    op.drop_table('game')
    # ### end Alembic commands ###
